"""Add CPMK tracking feature

Revision ID: 4522d0661aa0
Revises: 32b428bffa0f
Create Date: 2025-06-09 13:21:20.125080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4522d0661aa0'
down_revision = '32b428bffa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpmk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpmk_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cpmk', ['cpmk_id'], ['id'])

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpmk_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cpmk', ['cpmk_id'], ['id'])

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpmk_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cpmk', ['cpmk_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cpmk_id')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cpmk_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cpmk_id')

    op.drop_table('cpmk')
    # ### end Alembic commands ###
