"""Add is_resubmission_allowed to AssignmentSubmission

Revision ID: fd787053c267
Revises: a53cd34e2d40
Create Date: 2025-06-08 19:33:15.004759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd787053c267'
down_revision = 'a53cd34e2d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resubmission_allowed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.drop_column('is_resubmission_allowed')

    # ### end Alembic commands ###
